version: '3.3'  

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-master.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    restart: always
    depends_on:
      - redis-master
    ports:
      - "6380:6380"
    volumes:
      - ./redis/redis-slave1.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    restart: always
    depends_on:
      - redis-master
    ports:
      - "6381:6381"
    volumes:
      - ./redis/redis-slave2.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  sentinel1:
    image: redis:latest
    container_name: sentinel1
    restart: always
    depends_on:
      - redis-master
    command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]
    volumes:
      - ./redis/sentinel-1.conf:/etc/redis/sentinel.conf

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    depends_on:
      - redis-master
    ports:
      - "6389:6379"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  publisher:
    build: ./publisher
    container_name: publisher
    depends_on:
      - haproxy
    networks:
      - default

  subscriber:
    build: ./subscriber
    container_name: subscriber
    depends_on:
      - haproxy
    networks:
      - default

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis-master:6379"
    depends_on:
      - redis-master
  haproxy-exporter:
    image: prom/haproxy-exporter
    container_name: haproxy-exporter
    ports:
      - "9101:9101"
    depends_on:
      - haproxy
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana