global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy-exporter:9101']